package com.model;

/**
 * TJiaoyuan generated by MyEclipse Persistence Tools
 */

public class TJiaoyuan implements java.io.Serializable
{

	// Fields

	private Integer jiaojuanId;

	private Integer stuId;
	
	private int shitiId;

	private Integer timuId;

	private String timuDaan;

	// Constructors

	/** default constructor */
	public TJiaoyuan()
	{
	}

	/** full constructor */
	public TJiaoyuan(Integer stuId, Integer timuId, String timuDaan)
	{
		this.stuId = stuId;
		this.timuId = timuId;
		this.timuDaan = timuDaan;
	}

	// Property accessors

	public Integer getJiaojuanId()
	{
		return this.jiaojuanId;
	}

	public void setJiaojuanId(Integer jiaojuanId)
	{
		this.jiaojuanId = jiaojuanId;
	}

	public int getShitiId()
	{
		return shitiId;
	}

	public void setShitiId(int shitiId)
	{
		this.shitiId = shitiId;
	}

	public Integer getStuId()
	{
		return this.stuId;
	}

	public void setStuId(Integer stuId)
	{
		this.stuId = stuId;
	}

	public Integer getTimuId()
	{
		return this.timuId;
	}

	public void setTimuId(Integer timuId)
	{
		this.timuId = timuId;
	}

	public String getTimuDaan()
	{
		return this.timuDaan;
	}

	public void setTimuDaan(String timuDaan)
	{
		this.timuDaan = timuDaan;
	}

}