package com.model;

/**
 * TKecheng generated by MyEclipse Persistence Tools
 */

public class TKecheng implements java.io.Serializable
{

	private Integer kechengId;
	private String kechengName;
	private String del;
	
	
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public Integer getKechengId()
	{
		return kechengId;
	}
	public void setKechengId(Integer kechengId)
	{
		this.kechengId = kechengId;
	}
	public String getKechengName()
	{
		return kechengName;
	}
	public void setKechengName(String kechengName)
	{
		this.kechengName = kechengName;
	}

}