package com.model;

/**
 * TShiti generated by MyEclipse Persistence Tools
 */

public class TShiti implements java.io.Serializable
{

	private Integer shitiId;
	private String shitiName;
	private String shitiJieshao;
	private String timuIdList;
	private String shitiShijian;
	private String del;
	
	
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public Integer getShitiId()
	{
		return shitiId;
	}
	public void setShitiId(Integer shitiId)
	{
		this.shitiId = shitiId;
	}
	
	public String getTimuIdList()
	{
		return timuIdList;
	}
	public void setTimuIdList(String timuIdList)
	{
		this.timuIdList = timuIdList;
	}
	public String getShitiJieshao()
	{
		return shitiJieshao;
	}
	public void setShitiJieshao(String shitiJieshao)
	{
		this.shitiJieshao = shitiJieshao;
	}
	public String getShitiName()
	{
		return shitiName;
	}
	public void setShitiName(String shitiName)
	{
		this.shitiName = shitiName;
	}
	public String getShitiShijian()
	{
		return shitiShijian;
	}
	public void setShitiShijian(String shitiShijian)
	{
		this.shitiShijian = shitiShijian;
	}

}