package com.model;

/**
 * TTea generated by MyEclipse Persistence Tools
 */

public class TTea implements java.io.Serializable
{

	// Fields

	private Integer teaId;
	private String teaBianhao;
	private String teaRealname;
	private String teaSex;

	private String teaAge;
	private String loginPw;
	private String del;
	
	
	public Integer getTeaId() {
		return teaId;
	}
	public void setTeaId(Integer teaId) {
		this.teaId = teaId;
	}
	public String getTeaBianhao() {
		return teaBianhao;
	}
	public void setTeaBianhao(String teaBianhao) {
		this.teaBianhao = teaBianhao;
	}
	public String getTeaRealname() {
		return teaRealname;
	}
	public void setTeaRealname(String teaRealname) {
		this.teaRealname = teaRealname;
	}
	public String getTeaSex() {
		return teaSex;
	}
	public void setTeaSex(String teaSex) {
		this.teaSex = teaSex;
	}
	public String getTeaAge() {
		return teaAge;
	}
	public void setTeaAge(String teaAge) {
		this.teaAge = teaAge;
	}
	public String getLoginPw() {
		return loginPw;
	}
	public void setLoginPw(String loginPw) {
		this.loginPw = loginPw;
	}
	public String getDel() {
		return del;
	}
	public void setDel(String del) {
		this.del = del;
	}

}