package com.model;

/**
 * TTimu generated by MyEclipse Persistence Tools
 */

public class TTimu implements java.io.Serializable
{

	private Integer timuId;
	private String timuName;
	private String timuLeixing;
	private String timuXuanxianga;

	private String timuXuanxiangb;
	private String timuXuanxiangc;
	private String timuXuanxiangd;
	private String timuDaan;

	private Integer timuFenshu;
	private Integer kechengId;
	private String del;
	
	private TKecheng kecheng;
	private String timuDaanAsStu;//学生的答案。数据库没有此字段

	public String getDel()
	{
		return del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public TKecheng getKecheng()
	{
		return kecheng;
	}

	public void setKecheng(TKecheng kecheng)
	{
		this.kecheng = kecheng;
	}

	public Integer getKechengId()
	{
		return kechengId;
	}

	public void setKechengId(Integer kechengId)
	{
		this.kechengId = kechengId;
	}

	public String getTimuDaan()
	{
		return timuDaan;
	}

	public void setTimuDaan(String timuDaan)
	{
		this.timuDaan = timuDaan;
	}

	public String getTimuDaanAsStu()
	{
		return timuDaanAsStu;
	}

	public void setTimuDaanAsStu(String timuDaanAsStu)
	{
		this.timuDaanAsStu = timuDaanAsStu;
	}

	public Integer getTimuFenshu()
	{
		return timuFenshu;
	}

	public void setTimuFenshu(Integer timuFenshu)
	{
		this.timuFenshu = timuFenshu;
	}

	public Integer getTimuId()
	{
		return timuId;
	}

	public void setTimuId(Integer timuId)
	{
		this.timuId = timuId;
	}

	public String getTimuLeixing()
	{
		return timuLeixing;
	}

	public void setTimuLeixing(String timuLeixing)
	{
		this.timuLeixing = timuLeixing;
	}

	public String getTimuName()
	{
		return timuName;
	}

	public void setTimuName(String timuName)
	{
		this.timuName = timuName;
	}

	public String getTimuXuanxianga()
	{
		return timuXuanxianga;
	}

	public void setTimuXuanxianga(String timuXuanxianga)
	{
		this.timuXuanxianga = timuXuanxianga;
	}

	public String getTimuXuanxiangb()
	{
		return timuXuanxiangb;
	}

	public void setTimuXuanxiangb(String timuXuanxiangb)
	{
		this.timuXuanxiangb = timuXuanxiangb;
	}

	public String getTimuXuanxiangc()
	{
		return timuXuanxiangc;
	}

	public void setTimuXuanxiangc(String timuXuanxiangc)
	{
		this.timuXuanxiangc = timuXuanxiangc;
	}

	public String getTimuXuanxiangd()
	{
		return timuXuanxiangd;
	}

	public void setTimuXuanxiangd(String timuXuanxiangd)
	{
		this.timuXuanxiangd = timuXuanxiangd;
	}

}